name: GoReleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: build public files
        run: |
          npm install -g pnpm
          echo "清空原有数据"
          rm -rf ./public
          mkdir -p public
          echo '构建用户页面'
          cd ui && CI=false pnpm install && CI=false pnpm build && cd ..
          cp -r ui/build/* public/
          echo '构建前端数据完成'
          ls public/static
          git stash
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v1.18.2
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
